// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="filter_hls,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.154000,HLS_SYN_LAT=2076608,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=2314,HLS_SYN_LUT=1807}" *)

module filter_hls (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_in_TDATA,
        data_in_TVALID,
        data_in_TREADY,
        data_out_TDATA,
        data_out_TVALID,
        data_out_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state9 = 3'd4;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] data_in_TDATA;
input   data_in_TVALID;
output   data_in_TREADY;
output  [23:0] data_out_TDATA;
output   data_out_TVALID;
input   data_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [23:0] data_in_0_data_out;
wire    data_in_0_vld_in;
wire    data_in_0_vld_out;
wire    data_in_0_ack_in;
reg    data_in_0_ack_out;
reg   [23:0] data_in_0_payload_A;
reg   [23:0] data_in_0_payload_B;
reg    data_in_0_sel_rd;
reg    data_in_0_sel_wr;
wire    data_in_0_sel;
wire    data_in_0_load_A;
wire    data_in_0_load_B;
reg   [1:0] data_in_0_state;
wire    data_in_0_state_cmp_full;
reg   [23:0] data_out_1_data_out;
reg    data_out_1_vld_in;
wire    data_out_1_vld_out;
wire    data_out_1_ack_in;
wire    data_out_1_ack_out;
reg   [23:0] data_out_1_payload_A;
reg   [23:0] data_out_1_payload_B;
reg    data_out_1_sel_rd;
reg    data_out_1_sel_wr;
wire    data_out_1_sel;
wire    data_out_1_load_A;
wire    data_out_1_load_B;
reg   [1:0] data_out_1_state;
wire    data_out_1_state_cmp_full;
reg   [7:0] window_r_V_0_2;
reg   [7:0] window_g_V_0_2;
reg   [7:0] window_b_V_0_2;
reg   [7:0] window_r_V_1_2;
reg   [7:0] window_g_V_1_2;
reg   [7:0] window_b_V_1_2;
reg   [7:0] window_r_V_2_2;
reg   [7:0] window_g_V_2_2;
reg   [7:0] window_b_V_2_2;
wire   [10:0] lines_r_V_0_address0;
reg    lines_r_V_0_ce0;
wire   [7:0] lines_r_V_0_q0;
reg    lines_r_V_0_ce1;
reg    lines_r_V_0_we1;
wire   [10:0] lines_g_V_0_address0;
reg    lines_g_V_0_ce0;
wire   [7:0] lines_g_V_0_q0;
reg    lines_g_V_0_ce1;
reg    lines_g_V_0_we1;
wire   [10:0] lines_b_V_0_address0;
reg    lines_b_V_0_ce0;
wire   [7:0] lines_b_V_0_q0;
reg    lines_b_V_0_ce1;
reg    lines_b_V_0_we1;
wire   [10:0] lines_r_V_1_address0;
reg    lines_r_V_1_ce0;
wire   [7:0] lines_r_V_1_q0;
wire   [10:0] lines_r_V_1_address1;
reg    lines_r_V_1_ce1;
reg    lines_r_V_1_we1;
wire   [10:0] lines_g_V_1_address0;
reg    lines_g_V_1_ce0;
wire   [7:0] lines_g_V_1_q0;
wire   [10:0] lines_g_V_1_address1;
reg    lines_g_V_1_ce1;
reg    lines_g_V_1_we1;
wire   [10:0] lines_b_V_1_address0;
reg    lines_b_V_1_ce0;
wire   [7:0] lines_b_V_1_q0;
wire   [10:0] lines_b_V_1_address1;
reg    lines_b_V_1_ce1;
reg    lines_b_V_1_we1;
reg   [7:0] window_r_V_0_1;
reg   [7:0] window_g_V_0_1;
reg   [7:0] window_b_V_0_1;
reg   [7:0] window_r_V_1_1;
reg   [7:0] window_g_V_1_1;
reg   [7:0] window_b_V_1_1;
reg   [7:0] window_r_V_2_1;
reg   [7:0] window_g_V_2_1;
reg   [7:0] window_b_V_2_1;
reg    data_in_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_flag00000000;
reg   [0:0] exitcond_flatten_reg_1857;
reg   [0:0] or_cond_reg_1893;
reg    data_out_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] or_cond1_reg_1948;
reg   [0:0] ap_reg_pp0_iter4_or_cond1_reg_1948;
reg    ap_enable_reg_pp0_iter6;
reg   [0:0] ap_reg_pp0_iter5_or_cond1_reg_1948;
reg   [20:0] indvar_flatten_reg_290;
reg   [10:0] y_reg_301;
reg   [7:0] window_r_V_0_2_loc_1_reg_312;
reg   [7:0] window_g_V_0_2_loc_1_reg_322;
reg   [7:0] window_b_V_0_2_loc_1_reg_332;
reg   [7:0] window_r_V_1_2_loc_1_reg_342;
reg   [7:0] window_g_V_1_2_loc_1_reg_352;
reg   [7:0] window_b_V_1_2_loc_1_reg_362;
reg   [7:0] window_r_V_2_2_loc_1_reg_372;
reg   [7:0] window_g_V_2_2_loc_1_reg_382;
reg   [7:0] window_b_V_2_2_loc_1_reg_392;
reg   [10:0] x_reg_402;
reg   [7:0] window_r_V_0_2_loc_2_reg_413;
reg   [7:0] window_g_V_0_2_loc_2_reg_427;
reg   [7:0] window_b_V_0_2_loc_2_reg_441;
reg   [7:0] window_r_V_1_2_loc_2_reg_455;
reg   [7:0] window_g_V_1_2_loc_2_reg_469;
reg   [7:0] window_b_V_1_2_loc_2_reg_483;
reg   [7:0] window_r_V_2_2_loc_2_reg_497;
reg   [7:0] ap_reg_pp0_iter3_window_r_V_2_2_loc_2_reg_497;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op74_read_state3;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
reg    ap_block_state7_io;
wire    ap_block_state8_pp0_stage0_iter6;
reg    ap_block_state8_io;
reg    ap_block_pp0_stage0_flag00011001;
reg   [7:0] window_g_V_2_2_loc_2_reg_510;
reg   [7:0] ap_reg_pp0_iter3_window_g_V_2_2_loc_2_reg_510;
reg   [7:0] window_b_V_2_2_loc_2_reg_523;
reg   [7:0] ap_reg_pp0_iter3_window_b_V_2_2_loc_2_reg_523;
wire   [0:0] tmp_3_fu_578_p2;
reg   [0:0] tmp_3_reg_1852;
wire   [0:0] exitcond_flatten_fu_584_p2;
reg   [0:0] ap_reg_pp0_iter1_exitcond_flatten_reg_1857;
reg   [0:0] ap_reg_pp0_iter2_exitcond_flatten_reg_1857;
reg   [0:0] ap_reg_pp0_iter3_exitcond_flatten_reg_1857;
wire   [20:0] indvar_flatten_next_fu_590_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond_fu_596_p2;
reg   [0:0] exitcond_reg_1866;
wire   [10:0] x_mid2_fu_602_p3;
reg   [10:0] x_mid2_reg_1871;
reg   [10:0] ap_reg_pp0_iter1_x_mid2_reg_1871;
wire   [0:0] tmp_3_mid1_fu_630_p2;
reg   [0:0] tmp_3_mid1_reg_1879;
wire   [10:0] y_mid2_fu_636_p3;
wire   [0:0] tmp_5_fu_644_p2;
reg   [0:0] tmp_5_reg_1889;
reg   [0:0] ap_reg_pp0_iter1_tmp_5_reg_1889;
wire   [0:0] or_cond_fu_650_p2;
reg   [0:0] ap_reg_pp0_iter1_or_cond_reg_1893;
reg   [10:0] lines_r_V_0_addr_reg_1897;
reg   [10:0] lines_g_V_0_addr_reg_1903;
reg   [10:0] lines_b_V_0_addr_reg_1909;
wire   [7:0] tmp_2_fu_688_p1;
reg   [7:0] tmp_2_reg_1930;
reg   [7:0] data_in_g_V_load_new_reg_1936;
reg   [7:0] data_in_b_V_load_new_reg_1942;
wire   [0:0] or_cond1_fu_735_p2;
reg   [0:0] ap_reg_pp0_iter2_or_cond1_reg_1948;
reg   [0:0] ap_reg_pp0_iter3_or_cond1_reg_1948;
wire   [10:0] x_1_fu_741_p2;
wire   [19:0] tmp2_fu_1130_p2;
reg   [19:0] tmp2_reg_1957;
wire   [16:0] tmp5_fu_1136_p2;
reg   [16:0] tmp5_reg_1962;
wire   [17:0] tmp7_fu_1148_p2;
reg   [17:0] tmp7_reg_1967;
wire   [19:0] tmp9_fu_1166_p2;
reg   [19:0] tmp9_reg_1972;
wire   [16:0] tmp12_fu_1172_p2;
reg   [16:0] tmp12_reg_1977;
wire   [17:0] tmp14_fu_1184_p2;
reg   [17:0] tmp14_reg_1982;
wire   [19:0] tmp17_fu_1202_p2;
reg   [19:0] tmp17_reg_1987;
wire   [16:0] tmp20_fu_1208_p2;
reg   [16:0] tmp20_reg_1992;
wire   [17:0] tmp22_fu_1220_p2;
reg   [17:0] tmp22_reg_1997;
wire   [20:0] p_Val2_2_2_2_fu_1409_p2;
reg   [20:0] p_Val2_2_2_2_reg_2002;
wire   [19:0] p_Val2_2_2_2_cast_fu_1415_p2;
reg   [19:0] p_Val2_2_2_2_cast_reg_2007;
wire   [20:0] p_Val2_5_2_2_fu_1466_p2;
reg   [20:0] p_Val2_5_2_2_reg_2012;
wire   [19:0] p_Val2_5_2_2_cast_fu_1472_p2;
reg   [19:0] p_Val2_5_2_2_cast_reg_2017;
wire   [20:0] p_Val2_8_2_2_fu_1523_p2;
reg   [20:0] p_Val2_8_2_2_reg_2022;
wire   [19:0] p_Val2_8_2_2_cast_fu_1529_p2;
reg   [19:0] p_Val2_8_2_2_cast_reg_2027;
reg   [0:0] tmp_27_reg_2032;
reg   [0:0] tmp_29_reg_2038;
reg   [0:0] tmp_31_reg_2044;
wire   [19:0] p_Val2_s_6_fu_1576_p3;
reg   [19:0] p_Val2_s_6_reg_2050;
wire   [19:0] p_Val2_2_fu_1600_p3;
reg   [19:0] p_Val2_2_reg_2055;
wire   [19:0] p_Val2_1_fu_1624_p3;
reg   [19:0] p_Val2_1_reg_2060;
reg   [7:0] ret_V_cast_reg_2065;
wire   [9:0] tmp_35_fu_1641_p1;
reg   [9:0] tmp_35_reg_2070;
reg   [7:0] tmp_20_reg_2075;
reg   [7:0] ret_V_2_cast_reg_2081;
wire   [9:0] tmp_39_fu_1665_p1;
reg   [9:0] tmp_39_reg_2086;
reg   [7:0] tmp_23_reg_2091;
reg   [7:0] ret_V_4_cast_reg_2097;
wire   [9:0] tmp_43_fu_1689_p1;
reg   [9:0] tmp_43_reg_2102;
reg   [7:0] tmp_26_reg_2107;
wire   [23:0] data_out_b_V_addr_fu_1796_p4;
reg    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [7:0] window_r_V_0_2_loc_1_phi_fu_315_p4;
reg   [7:0] window_g_V_0_2_loc_1_phi_fu_325_p4;
reg   [7:0] window_b_V_0_2_loc_1_phi_fu_335_p4;
reg   [7:0] window_r_V_1_2_loc_1_phi_fu_345_p4;
reg   [7:0] window_g_V_1_2_loc_1_phi_fu_355_p4;
reg   [7:0] window_b_V_1_2_loc_1_phi_fu_365_p4;
reg   [7:0] window_r_V_2_2_loc_1_phi_fu_375_p4;
reg   [7:0] window_g_V_2_2_loc_1_phi_fu_385_p4;
reg   [7:0] window_b_V_2_2_loc_1_phi_fu_395_p4;
reg   [10:0] x_phi_fu_406_p4;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_r_V_0_2_loc_2_reg_413;
reg   [7:0] window_r_V_0_2_loc_2_phi_fu_418_p4;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_r_V_0_2_loc_2_reg_413;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_g_V_0_2_loc_2_reg_427;
reg   [7:0] window_g_V_0_2_loc_2_phi_fu_432_p4;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_g_V_0_2_loc_2_reg_427;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_b_V_0_2_loc_2_reg_441;
reg   [7:0] window_b_V_0_2_loc_2_phi_fu_446_p4;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_b_V_0_2_loc_2_reg_441;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_r_V_1_2_loc_2_reg_455;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_r_V_1_2_loc_2_reg_455;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_g_V_1_2_loc_2_reg_469;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_g_V_1_2_loc_2_reg_469;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_b_V_1_2_loc_2_reg_483;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_b_V_1_2_loc_2_reg_483;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_r_V_2_2_loc_2_reg_497;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_r_V_2_2_loc_2_reg_497;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_g_V_2_2_loc_2_reg_510;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_g_V_2_2_loc_2_reg_510;
wire   [7:0] ap_phi_precharge_reg_pp0_iter1_window_b_V_2_2_loc_2_reg_523;
reg   [7:0] ap_phi_precharge_reg_pp0_iter2_window_b_V_2_2_loc_2_reg_523;
wire   [63:0] tmp_7_fu_661_p1;
wire   [63:0] tmp_8_fu_878_p1;
reg    ap_block_pp0_stage0_flag00001001;
wire   [10:0] y_s_fu_610_p2;
wire   [0:0] tmp_1_mid1_fu_616_p2;
wire   [0:0] tmp_1_fu_572_p2;
wire   [0:0] tmp_1_mid2_fu_622_p3;
wire   [0:0] tmp_9_fu_730_p2;
wire   [0:0] tmp_3_mid2_fu_656_p3;
wire   [14:0] p_Val2_s_fu_884_p3;
wire   [14:0] p_Val2_4_fu_896_p3;
wire   [14:0] p_Val2_7_fu_908_p3;
wire   [15:0] p_Val2_1_0_1_fu_920_p3;
wire   [15:0] p_Val2_4_0_1_fu_932_p3;
wire   [15:0] p_Val2_7_0_1_fu_944_p3;
wire   [14:0] p_Val2_1_0_2_fu_956_p3;
wire   [14:0] p_Val2_4_0_2_fu_968_p3;
wire   [14:0] p_Val2_7_0_2_fu_980_p3;
wire   [15:0] p_Val2_1_1_fu_992_p3;
wire   [15:0] p_Val2_4_1_fu_1004_p3;
wire   [15:0] p_Val2_7_1_fu_1016_p3;
wire   [18:0] p_shl2_fu_1028_p3;
wire   [16:0] p_shl3_fu_1040_p3;
wire   [19:0] p_shl3_cast_fu_1048_p1;
wire   [19:0] p_shl2_cast_fu_1036_p1;
wire   [18:0] p_shl4_fu_1058_p3;
wire   [16:0] p_shl5_fu_1070_p3;
wire   [19:0] p_shl5_cast_fu_1078_p1;
wire   [19:0] p_shl4_cast_fu_1066_p1;
wire   [18:0] p_shl6_fu_1088_p3;
wire   [16:0] p_shl7_fu_1100_p3;
wire   [19:0] p_shl7_cast_fu_1108_p1;
wire   [19:0] p_shl6_cast_fu_1096_p1;
wire   [14:0] p_Val2_1_2_2_fu_1118_p3;
wire   [19:0] p_Val2_1_0_1_cast_fu_928_p1;
wire   [19:0] p_Val2_1_1_1_fu_1052_p2;
wire   [16:0] p_Val2_1_1_cast_fu_1000_p1;
wire   [16:0] p_Val2_11_cast_fu_892_p1;
wire   [17:0] p_Val2_1_2_2_cast_fu_1126_p1;
wire   [17:0] p_Val2_1_0_2_cast_fu_964_p1;
wire   [17:0] tmp6_fu_1142_p2;
wire   [14:0] p_Val2_4_2_2_fu_1154_p3;
wire   [19:0] p_Val2_4_0_1_cast_fu_940_p1;
wire   [19:0] p_Val2_4_1_1_fu_1082_p2;
wire   [16:0] p_Val2_4_1_cast_fu_1012_p1;
wire   [16:0] p_Val2_4_cast_fu_904_p1;
wire   [17:0] p_Val2_4_2_2_cast_fu_1162_p1;
wire   [17:0] p_Val2_4_0_2_cast_fu_976_p1;
wire   [17:0] tmp13_fu_1178_p2;
wire   [14:0] p_Val2_7_2_2_fu_1190_p3;
wire   [19:0] p_Val2_7_0_1_cast_fu_952_p1;
wire   [19:0] p_Val2_7_1_1_fu_1112_p2;
wire   [16:0] p_Val2_7_1_cast_fu_1024_p1;
wire   [16:0] p_Val2_7_cast_fu_916_p1;
wire   [17:0] p_Val2_7_2_2_cast_fu_1198_p1;
wire   [17:0] p_Val2_7_0_2_cast_fu_988_p1;
wire   [17:0] tmp21_fu_1214_p2;
wire   [15:0] p_Val2_1_1_2_fu_1256_p3;
wire   [15:0] p_Val2_4_1_2_fu_1268_p3;
wire   [15:0] p_Val2_7_1_2_fu_1280_p3;
wire   [14:0] p_Val2_1_2_fu_1292_p3;
wire   [14:0] p_Val2_4_2_fu_1304_p3;
wire   [14:0] p_Val2_7_2_fu_1316_p3;
wire   [15:0] p_Val2_1_2_1_fu_1328_p3;
wire   [15:0] p_Val2_4_2_1_fu_1340_p3;
wire   [15:0] p_Val2_7_2_1_fu_1352_p3;
wire   [16:0] p_Val2_1_2_cast_fu_1300_p1;
wire   [16:0] p_Val2_1_2_1_cast_fu_1336_p1;
wire   [16:0] tmp1_fu_1364_p2;
wire   [19:0] p_Val2_1_1_2_cast_fu_1264_p1;
wire   [19:0] tmp23_cast_fu_1370_p1;
wire   [19:0] tmp3_fu_1374_p2;
wire   [19:0] tmp4_fu_1379_p2;
wire   [18:0] tmp27_cast_fu_1389_p1;
wire   [18:0] tmp28_cast_fu_1392_p1;
wire   [18:0] tmp8_fu_1395_p2;
wire  signed [20:0] tmp22_cast_fu_1385_p1;
wire   [20:0] tmp26_cast_fu_1401_p1;
wire   [19:0] tmp_s_fu_1405_p1;
wire   [16:0] p_Val2_4_2_cast_fu_1312_p1;
wire   [16:0] p_Val2_4_2_1_cast_fu_1348_p1;
wire   [16:0] tmp_fu_1421_p2;
wire   [19:0] p_Val2_4_1_2_cast_fu_1276_p1;
wire   [19:0] tmp31_cast_fu_1427_p1;
wire   [19:0] tmp10_fu_1431_p2;
wire   [19:0] tmp11_fu_1436_p2;
wire   [18:0] tmp35_cast_fu_1446_p1;
wire   [18:0] tmp36_cast_fu_1449_p1;
wire   [18:0] tmp15_fu_1452_p2;
wire  signed [20:0] tmp30_cast_fu_1442_p1;
wire   [20:0] tmp34_cast_fu_1458_p1;
wire   [19:0] tmp_6_fu_1462_p1;
wire   [16:0] p_Val2_7_2_cast_fu_1324_p1;
wire   [16:0] p_Val2_7_2_1_cast_fu_1360_p1;
wire   [16:0] tmp16_fu_1478_p2;
wire   [19:0] p_Val2_7_1_2_cast_fu_1288_p1;
wire   [19:0] tmp39_cast_fu_1484_p1;
wire   [19:0] tmp18_fu_1488_p2;
wire   [19:0] tmp19_fu_1493_p2;
wire   [18:0] tmp43_cast_fu_1503_p1;
wire   [18:0] tmp44_cast_fu_1506_p1;
wire   [18:0] tmp23_fu_1509_p2;
wire  signed [20:0] tmp38_cast_fu_1499_p1;
wire   [20:0] tmp42_cast_fu_1515_p1;
wire   [19:0] tmp_10_fu_1519_p1;
wire   [0:0] tmp_11_fu_1559_p2;
wire   [0:0] tmp_12_fu_1571_p2;
wire   [19:0] p_sum_r_cast_fu_1564_p3;
wire   [0:0] tmp_13_fu_1583_p2;
wire   [0:0] tmp_14_fu_1595_p2;
wire   [19:0] p_sum_g_cast_fu_1588_p3;
wire   [0:0] tmp_15_fu_1607_p2;
wire   [0:0] tmp_19_fu_1619_p2;
wire   [19:0] p_sum_b_cast_fu_1612_p3;
wire   [0:0] tmp_16_fu_1710_p2;
wire   [7:0] ret_V_1_fu_1715_p2;
wire   [0:0] tmp_33_fu_1703_p3;
wire   [7:0] tmp_21_fu_1720_p3;
wire   [0:0] tmp_17_fu_1741_p2;
wire   [7:0] ret_V_3_fu_1746_p2;
wire   [0:0] tmp_37_fu_1734_p3;
wire   [7:0] tmp_24_fu_1751_p3;
wire   [0:0] tmp_18_fu_1772_p2;
wire   [7:0] ret_V_5_fu_1777_p2;
wire   [0:0] tmp_41_fu_1765_p3;
wire   [7:0] tmp_28_fu_1782_p3;
wire   [7:0] tmp_30_fu_1789_p3;
wire   [7:0] tmp_25_fu_1758_p3;
wire   [7:0] tmp_22_fu_1727_p3;
wire    ap_CS_fsm_state9;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_434;
reg    ap_condition_609;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 data_in_0_sel_rd = 1'b0;
#0 data_in_0_sel_wr = 1'b0;
#0 data_in_0_state = 2'd0;
#0 data_out_1_sel_rd = 1'b0;
#0 data_out_1_sel_wr = 1'b0;
#0 data_out_1_state = 2'd0;
#0 window_r_V_0_2 = 8'd0;
#0 window_g_V_0_2 = 8'd0;
#0 window_b_V_0_2 = 8'd0;
#0 window_r_V_1_2 = 8'd0;
#0 window_g_V_1_2 = 8'd0;
#0 window_b_V_1_2 = 8'd0;
#0 window_r_V_2_2 = 8'd0;
#0 window_g_V_2_2 = 8'd0;
#0 window_b_V_2_2 = 8'd0;
#0 window_r_V_0_1 = 8'd0;
#0 window_g_V_0_1 = 8'd0;
#0 window_b_V_0_1 = 8'd0;
#0 window_r_V_1_1 = 8'd0;
#0 window_g_V_1_1 = 8'd0;
#0 window_b_V_1_1 = 8'd0;
#0 window_r_V_2_1 = 8'd0;
#0 window_g_V_2_1 = 8'd0;
#0 window_b_V_2_1 = 8'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

filter_hls_lines_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lines_r_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lines_r_V_0_address0),
    .ce0(lines_r_V_0_ce0),
    .q0(lines_r_V_0_q0),
    .address1(lines_r_V_0_addr_reg_1897),
    .ce1(lines_r_V_0_ce1),
    .we1(lines_r_V_0_we1),
    .d1(lines_r_V_1_q0)
);

filter_hls_lines_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lines_g_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lines_g_V_0_address0),
    .ce0(lines_g_V_0_ce0),
    .q0(lines_g_V_0_q0),
    .address1(lines_g_V_0_addr_reg_1903),
    .ce1(lines_g_V_0_ce1),
    .we1(lines_g_V_0_we1),
    .d1(lines_g_V_1_q0)
);

filter_hls_lines_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lines_b_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lines_b_V_0_address0),
    .ce0(lines_b_V_0_ce0),
    .q0(lines_b_V_0_q0),
    .address1(lines_b_V_0_addr_reg_1909),
    .ce1(lines_b_V_0_ce1),
    .we1(lines_b_V_0_we1),
    .d1(lines_b_V_1_q0)
);

filter_hls_lines_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lines_r_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lines_r_V_1_address0),
    .ce0(lines_r_V_1_ce0),
    .q0(lines_r_V_1_q0),
    .address1(lines_r_V_1_address1),
    .ce1(lines_r_V_1_ce1),
    .we1(lines_r_V_1_we1),
    .d1(tmp_2_reg_1930)
);

filter_hls_lines_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lines_g_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lines_g_V_1_address0),
    .ce0(lines_g_V_1_ce0),
    .q0(lines_g_V_1_q0),
    .address1(lines_g_V_1_address1),
    .ce1(lines_g_V_1_ce1),
    .we1(lines_g_V_1_we1),
    .d1(data_in_g_V_load_new_reg_1936)
);

filter_hls_lines_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lines_b_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lines_b_V_1_address0),
    .ce0(lines_b_V_1_ce0),
    .q0(lines_b_V_1_q0),
    .address1(lines_b_V_1_address1),
    .ce1(lines_b_V_1_ce1),
    .we1(lines_b_V_1_we1),
    .d1(data_in_b_V_load_new_reg_1942)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 ^ 1'b1);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_in_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == data_in_0_ack_out) & (1'b1 == data_in_0_vld_out))) begin
            data_in_0_sel_rd <= ~data_in_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_in_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == data_in_0_vld_in) & (1'b1 == data_in_0_ack_in))) begin
            data_in_0_sel_wr <= ~data_in_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_in_0_state <= 2'd0;
    end else begin
        if ((((1'b0 == data_in_0_vld_in) & (1'b1 == data_in_0_ack_out) & (data_in_0_state == 2'd3)) | ((1'b0 == data_in_0_vld_in) & (data_in_0_state == 2'd2)))) begin
            data_in_0_state <= 2'd2;
        end else if ((((1'b1 == data_in_0_vld_in) & (1'b0 == data_in_0_ack_out) & (data_in_0_state == 2'd3)) | ((1'b0 == data_in_0_ack_out) & (data_in_0_state == 2'd1)))) begin
            data_in_0_state <= 2'd1;
        end else if ((((1'b1 == data_in_0_vld_in) & (data_in_0_state == 2'd2)) | ((1'b1 == data_in_0_ack_out) & (data_in_0_state == 2'd1)) | ((data_in_0_state == 2'd3) & ~((1'b1 == data_in_0_vld_in) & (1'b0 == data_in_0_ack_out)) & ~((1'b0 == data_in_0_vld_in) & (1'b1 == data_in_0_ack_out))))) begin
            data_in_0_state <= 2'd3;
        end else begin
            data_in_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_out_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == data_out_1_ack_out) & (1'b1 == data_out_1_vld_out))) begin
            data_out_1_sel_rd <= ~data_out_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_out_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == data_out_1_vld_in) & (1'b1 == data_out_1_ack_in))) begin
            data_out_1_sel_wr <= ~data_out_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_out_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == data_out_1_vld_in) & (1'b1 == data_out_1_ack_out) & (2'd3 == data_out_1_state)) | ((1'b0 == data_out_1_vld_in) & (2'd2 == data_out_1_state)))) begin
            data_out_1_state <= 2'd2;
        end else if ((((1'b1 == data_out_1_vld_in) & (1'b0 == data_out_1_ack_out) & (2'd3 == data_out_1_state)) | ((1'b0 == data_out_1_ack_out) & (2'd1 == data_out_1_state)))) begin
            data_out_1_state <= 2'd1;
        end else if ((((1'b1 == data_out_1_vld_in) & (2'd2 == data_out_1_state)) | ((1'b1 == data_out_1_ack_out) & (2'd1 == data_out_1_state)) | ((2'd3 == data_out_1_state) & ~((1'b1 == data_out_1_vld_in) & (1'b0 == data_out_1_ack_out)) & ~((1'b0 == data_out_1_vld_in) & (1'b1 == data_out_1_ack_out))))) begin
            data_out_1_state <= 2'd3;
        end else begin
            data_out_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == tmp_5_reg_1889))) begin
            ap_phi_precharge_reg_pp0_iter2_window_b_V_0_2_loc_2_reg_441 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_b_V_0_2_loc_2_reg_441 <= ap_phi_precharge_reg_pp0_iter1_window_b_V_0_2_loc_2_reg_441;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == tmp_5_reg_1889))) begin
            ap_phi_precharge_reg_pp0_iter2_window_b_V_1_2_loc_2_reg_483 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_b_V_1_2_loc_2_reg_483 <= ap_phi_precharge_reg_pp0_iter1_window_b_V_1_2_loc_2_reg_483;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == or_cond_reg_1893))) begin
            ap_phi_precharge_reg_pp0_iter2_window_b_V_2_2_loc_2_reg_523 <= 8'd0;
        end else if (((1'd0 == exitcond_flatten_reg_1857) & (1'd1 == or_cond_reg_1893))) begin
            ap_phi_precharge_reg_pp0_iter2_window_b_V_2_2_loc_2_reg_523 <= {{data_in_0_data_out[23:16]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_b_V_2_2_loc_2_reg_523 <= ap_phi_precharge_reg_pp0_iter1_window_b_V_2_2_loc_2_reg_523;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == tmp_5_reg_1889))) begin
            ap_phi_precharge_reg_pp0_iter2_window_g_V_0_2_loc_2_reg_427 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_g_V_0_2_loc_2_reg_427 <= ap_phi_precharge_reg_pp0_iter1_window_g_V_0_2_loc_2_reg_427;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == tmp_5_reg_1889))) begin
            ap_phi_precharge_reg_pp0_iter2_window_g_V_1_2_loc_2_reg_469 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_g_V_1_2_loc_2_reg_469 <= ap_phi_precharge_reg_pp0_iter1_window_g_V_1_2_loc_2_reg_469;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == or_cond_reg_1893))) begin
            ap_phi_precharge_reg_pp0_iter2_window_g_V_2_2_loc_2_reg_510 <= 8'd0;
        end else if (((1'd0 == exitcond_flatten_reg_1857) & (1'd1 == or_cond_reg_1893))) begin
            ap_phi_precharge_reg_pp0_iter2_window_g_V_2_2_loc_2_reg_510 <= {{data_in_0_data_out[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_g_V_2_2_loc_2_reg_510 <= ap_phi_precharge_reg_pp0_iter1_window_g_V_2_2_loc_2_reg_510;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == tmp_5_reg_1889))) begin
            ap_phi_precharge_reg_pp0_iter2_window_r_V_0_2_loc_2_reg_413 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_r_V_0_2_loc_2_reg_413 <= ap_phi_precharge_reg_pp0_iter1_window_r_V_0_2_loc_2_reg_413;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == tmp_5_reg_1889))) begin
            ap_phi_precharge_reg_pp0_iter2_window_r_V_1_2_loc_2_reg_455 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_r_V_1_2_loc_2_reg_455 <= ap_phi_precharge_reg_pp0_iter1_window_r_V_1_2_loc_2_reg_455;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == or_cond_reg_1893))) begin
            ap_phi_precharge_reg_pp0_iter2_window_r_V_2_2_loc_2_reg_497 <= 8'd0;
        end else if (((1'd0 == exitcond_flatten_reg_1857) & (1'd1 == or_cond_reg_1893))) begin
            ap_phi_precharge_reg_pp0_iter2_window_r_V_2_2_loc_2_reg_497 <= tmp_2_fu_688_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_precharge_reg_pp0_iter2_window_r_V_2_2_loc_2_reg_497 <= ap_phi_precharge_reg_pp0_iter1_window_r_V_2_2_loc_2_reg_497;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_584_p2))) begin
        indvar_flatten_reg_290 <= indvar_flatten_next_fu_590_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_290 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_609 == 1'b1)) begin
        if ((1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_b_V_0_2 <= lines_b_V_0_q0;
        end else if ((1'd0 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_b_V_0_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_b_V_0_2_loc_1_reg_332 <= window_b_V_0_2_loc_2_reg_441;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_b_V_0_2_loc_1_reg_332 <= window_b_V_0_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        if (((1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
            window_b_V_0_2_loc_2_reg_441 <= lines_b_V_0_q0;
        end else if ((1'b1 == 1'b1)) begin
            window_b_V_0_2_loc_2_reg_441 <= ap_phi_precharge_reg_pp0_iter2_window_b_V_0_2_loc_2_reg_441;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_609 == 1'b1)) begin
        if ((1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_b_V_1_2 <= lines_b_V_1_q0;
        end else if ((1'd0 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_b_V_1_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_b_V_1_2_loc_1_reg_362 <= window_b_V_1_2_loc_2_reg_483;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_b_V_1_2_loc_1_reg_362 <= window_b_V_1_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        if (((1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
            window_b_V_1_2_loc_2_reg_483 <= lines_b_V_1_q0;
        end else if ((1'b1 == 1'b1)) begin
            window_b_V_1_2_loc_2_reg_483 <= ap_phi_precharge_reg_pp0_iter2_window_b_V_1_2_loc_2_reg_483;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op74_read_state3)) begin
            window_b_V_2_2 <= {{data_in_0_data_out[23:16]}};
        end else if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == or_cond_reg_1893))) begin
            window_b_V_2_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_1857))) begin
        window_b_V_2_2_loc_1_reg_392 <= ap_reg_pp0_iter3_window_b_V_2_2_loc_2_reg_523;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_b_V_2_2_loc_1_reg_392 <= window_b_V_2_2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_609 == 1'b1)) begin
        if ((1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_g_V_0_2 <= lines_g_V_0_q0;
        end else if ((1'd0 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_g_V_0_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_g_V_0_2_loc_1_reg_322 <= window_g_V_0_2_loc_2_reg_427;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_g_V_0_2_loc_1_reg_322 <= window_g_V_0_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        if (((1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
            window_g_V_0_2_loc_2_reg_427 <= lines_g_V_0_q0;
        end else if ((1'b1 == 1'b1)) begin
            window_g_V_0_2_loc_2_reg_427 <= ap_phi_precharge_reg_pp0_iter2_window_g_V_0_2_loc_2_reg_427;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_609 == 1'b1)) begin
        if ((1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_g_V_1_2 <= lines_g_V_1_q0;
        end else if ((1'd0 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_g_V_1_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_g_V_1_2_loc_1_reg_352 <= window_g_V_1_2_loc_2_reg_469;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_g_V_1_2_loc_1_reg_352 <= window_g_V_1_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        if (((1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
            window_g_V_1_2_loc_2_reg_469 <= lines_g_V_1_q0;
        end else if ((1'b1 == 1'b1)) begin
            window_g_V_1_2_loc_2_reg_469 <= ap_phi_precharge_reg_pp0_iter2_window_g_V_1_2_loc_2_reg_469;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op74_read_state3)) begin
            window_g_V_2_2 <= {{data_in_0_data_out[15:8]}};
        end else if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == or_cond_reg_1893))) begin
            window_g_V_2_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_1857))) begin
        window_g_V_2_2_loc_1_reg_382 <= ap_reg_pp0_iter3_window_g_V_2_2_loc_2_reg_510;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_g_V_2_2_loc_1_reg_382 <= window_g_V_2_2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_609 == 1'b1)) begin
        if ((1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_r_V_0_2 <= lines_r_V_0_q0;
        end else if ((1'd0 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_r_V_0_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_r_V_0_2_loc_1_reg_312 <= window_r_V_0_2_loc_2_reg_413;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_r_V_0_2_loc_1_reg_312 <= window_r_V_0_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        if (((1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
            window_r_V_0_2_loc_2_reg_413 <= lines_r_V_0_q0;
        end else if ((1'b1 == 1'b1)) begin
            window_r_V_0_2_loc_2_reg_413 <= ap_phi_precharge_reg_pp0_iter2_window_r_V_0_2_loc_2_reg_413;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_609 == 1'b1)) begin
        if ((1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_r_V_1_2 <= lines_r_V_1_q0;
        end else if ((1'd0 == ap_reg_pp0_iter1_tmp_5_reg_1889)) begin
            window_r_V_1_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_r_V_1_2_loc_1_reg_342 <= window_r_V_1_2_loc_2_reg_455;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_r_V_1_2_loc_1_reg_342 <= window_r_V_1_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        if (((1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
            window_r_V_1_2_loc_2_reg_455 <= lines_r_V_1_q0;
        end else if ((1'b1 == 1'b1)) begin
            window_r_V_1_2_loc_2_reg_455 <= ap_phi_precharge_reg_pp0_iter2_window_r_V_1_2_loc_2_reg_455;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_434 == 1'b1)) begin
        if ((1'b1 == ap_predicate_op74_read_state3)) begin
            window_r_V_2_2 <= tmp_2_fu_688_p1;
        end else if (((1'd0 == exitcond_flatten_reg_1857) & (1'd0 == or_cond_reg_1893))) begin
            window_r_V_2_2 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_1857))) begin
        window_r_V_2_2_loc_1_reg_372 <= ap_reg_pp0_iter3_window_r_V_2_2_loc_2_reg_497;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_r_V_2_2_loc_1_reg_372 <= window_r_V_2_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond_flatten_reg_1857) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        x_reg_402 <= x_1_fu_741_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        x_reg_402 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_584_p2))) begin
        y_reg_301 <= y_mid2_fu_636_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        y_reg_301 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter1_exitcond_flatten_reg_1857 <= exitcond_flatten_reg_1857;
        ap_reg_pp0_iter1_or_cond_reg_1893 <= or_cond_reg_1893;
        ap_reg_pp0_iter1_tmp_5_reg_1889 <= tmp_5_reg_1889;
        ap_reg_pp0_iter1_x_mid2_reg_1871 <= x_mid2_reg_1871;
        exitcond_flatten_reg_1857 <= exitcond_flatten_fu_584_p2;
        or_cond1_reg_1948 <= or_cond1_fu_735_p2;
        tmp_3_reg_1852 <= tmp_3_fu_578_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
        ap_reg_pp0_iter2_exitcond_flatten_reg_1857 <= ap_reg_pp0_iter1_exitcond_flatten_reg_1857;
        ap_reg_pp0_iter2_or_cond1_reg_1948 <= or_cond1_reg_1948;
        ap_reg_pp0_iter3_exitcond_flatten_reg_1857 <= ap_reg_pp0_iter2_exitcond_flatten_reg_1857;
        ap_reg_pp0_iter3_or_cond1_reg_1948 <= ap_reg_pp0_iter2_or_cond1_reg_1948;
        ap_reg_pp0_iter3_window_b_V_2_2_loc_2_reg_523 <= window_b_V_2_2_loc_2_reg_523;
        ap_reg_pp0_iter3_window_g_V_2_2_loc_2_reg_510 <= window_g_V_2_2_loc_2_reg_510;
        ap_reg_pp0_iter3_window_r_V_2_2_loc_2_reg_497 <= window_r_V_2_2_loc_2_reg_497;
        ap_reg_pp0_iter4_or_cond1_reg_1948 <= ap_reg_pp0_iter3_or_cond1_reg_1948;
        ap_reg_pp0_iter5_or_cond1_reg_1948 <= ap_reg_pp0_iter4_or_cond1_reg_1948;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == data_in_0_load_A)) begin
        data_in_0_payload_A <= data_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == data_in_0_load_B)) begin
        data_in_0_payload_B <= data_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_predicate_op74_read_state3) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        data_in_b_V_load_new_reg_1942 <= {{data_in_0_data_out[23:16]}};
        data_in_g_V_load_new_reg_1936 <= {{data_in_0_data_out[15:8]}};
        tmp_2_reg_1930 <= tmp_2_fu_688_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == data_out_1_load_A)) begin
        data_out_1_payload_A <= data_out_b_V_addr_fu_1796_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == data_out_1_load_B)) begin
        data_out_1_payload_B <= data_out_b_V_addr_fu_1796_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_flatten_fu_584_p2))) begin
        exitcond_reg_1866 <= exitcond_fu_596_p2;
        or_cond_reg_1893 <= or_cond_fu_650_p2;
        tmp_3_mid1_reg_1879 <= tmp_3_mid1_fu_630_p2;
        tmp_5_reg_1889 <= tmp_5_fu_644_p2;
        x_mid2_reg_1871 <= x_mid2_fu_602_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'd0 == exitcond_flatten_reg_1857) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd1 == tmp_5_reg_1889))) begin
        lines_b_V_0_addr_reg_1909 <= tmp_7_fu_661_p1;
        lines_g_V_0_addr_reg_1903 <= tmp_7_fu_661_p1;
        lines_r_V_0_addr_reg_1897 <= tmp_7_fu_661_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd1 == ap_reg_pp0_iter3_or_cond1_reg_1948))) begin
        p_Val2_1_reg_2060[19 : 7] <= p_Val2_1_fu_1624_p3[19 : 7];
        p_Val2_2_reg_2055[19 : 7] <= p_Val2_2_fu_1600_p3[19 : 7];
        p_Val2_s_6_reg_2050[19 : 7] <= p_Val2_s_6_fu_1576_p3[19 : 7];
        ret_V_2_cast_reg_2081 <= {{p_Val2_2_fu_1600_p3[17:10]}};
        ret_V_4_cast_reg_2097 <= {{p_Val2_1_fu_1624_p3[17:10]}};
        ret_V_cast_reg_2065 <= {{p_Val2_s_6_fu_1576_p3[17:10]}};
        tmp_20_reg_2075 <= {{p_Val2_s_6_fu_1576_p3[17:10]}};
        tmp_23_reg_2091 <= {{p_Val2_2_fu_1600_p3[17:10]}};
        tmp_26_reg_2107 <= {{p_Val2_1_fu_1624_p3[17:10]}};
        tmp_35_reg_2070[9 : 7] <= tmp_35_fu_1641_p1[9 : 7];
        tmp_39_reg_2086[9 : 7] <= tmp_39_fu_1665_p1[9 : 7];
        tmp_43_reg_2102[9 : 7] <= tmp_43_fu_1689_p1[9 : 7];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd1 == ap_reg_pp0_iter2_or_cond1_reg_1948))) begin
        p_Val2_2_2_2_cast_reg_2007[19 : 7] <= p_Val2_2_2_2_cast_fu_1415_p2[19 : 7];
        p_Val2_2_2_2_reg_2002[20 : 7] <= p_Val2_2_2_2_fu_1409_p2[20 : 7];
        p_Val2_5_2_2_cast_reg_2017[19 : 7] <= p_Val2_5_2_2_cast_fu_1472_p2[19 : 7];
        p_Val2_5_2_2_reg_2012[20 : 7] <= p_Val2_5_2_2_fu_1466_p2[20 : 7];
        p_Val2_8_2_2_cast_reg_2027[19 : 7] <= p_Val2_8_2_2_cast_fu_1529_p2[19 : 7];
        p_Val2_8_2_2_reg_2022[20 : 7] <= p_Val2_8_2_2_fu_1523_p2[20 : 7];
        tmp_27_reg_2032 <= p_Val2_2_2_2_fu_1409_p2[32'd20];
        tmp_29_reg_2038 <= p_Val2_5_2_2_fu_1466_p2[32'd20];
        tmp_31_reg_2044 <= p_Val2_8_2_2_fu_1523_p2[32'd20];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd1 == or_cond1_reg_1948))) begin
        tmp12_reg_1977[16 : 7] <= tmp12_fu_1172_p2[16 : 7];
        tmp14_reg_1982[17 : 7] <= tmp14_fu_1184_p2[17 : 7];
        tmp17_reg_1987[19 : 8] <= tmp17_fu_1202_p2[19 : 8];
        tmp20_reg_1992[16 : 7] <= tmp20_fu_1208_p2[16 : 7];
        tmp22_reg_1997[17 : 7] <= tmp22_fu_1220_p2[17 : 7];
        tmp2_reg_1957[19 : 8] <= tmp2_fu_1130_p2[19 : 8];
        tmp5_reg_1962[16 : 7] <= tmp5_fu_1136_p2[16 : 7];
        tmp7_reg_1967[17 : 7] <= tmp7_fu_1148_p2[17 : 7];
        tmp9_reg_1972[19 : 8] <= tmp9_fu_1166_p2[19 : 8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857))) begin
        window_b_V_0_1 <= window_b_V_0_2_loc_1_phi_fu_335_p4;
        window_b_V_1_1 <= window_b_V_1_2_loc_1_phi_fu_365_p4;
        window_g_V_0_1 <= window_g_V_0_2_loc_1_phi_fu_325_p4;
        window_g_V_1_1 <= window_g_V_1_2_loc_1_phi_fu_355_p4;
        window_r_V_0_1 <= window_r_V_0_2_loc_1_phi_fu_315_p4;
        window_r_V_1_1 <= window_r_V_1_2_loc_1_phi_fu_345_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_b_V_2_1 <= window_b_V_2_2_loc_1_phi_fu_395_p4;
        window_g_V_2_1 <= window_g_V_2_2_loc_1_phi_fu_385_p4;
        window_r_V_2_1 <= window_r_V_2_2_loc_1_phi_fu_375_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        window_b_V_2_2_loc_2_reg_523 <= ap_phi_precharge_reg_pp0_iter2_window_b_V_2_2_loc_2_reg_523;
        window_g_V_2_2_loc_2_reg_510 <= ap_phi_precharge_reg_pp0_iter2_window_g_V_2_2_loc_2_reg_510;
        window_r_V_2_2_loc_2_reg_497 <= ap_phi_precharge_reg_pp0_iter2_window_r_V_2_2_loc_2_reg_497;
    end
end

always @ (*) begin
    if ((1'd1 == exitcond_flatten_fu_584_p2)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (data_out_1_ack_in == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3) & (1'b0 == ap_enable_reg_pp0_iter4) & (1'b0 == ap_enable_reg_pp0_iter5) & (1'b0 == ap_enable_reg_pp0_iter6))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (data_out_1_ack_in == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_predicate_op74_read_state3) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        data_in_0_ack_out = 1'b1;
    end else begin
        data_in_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == data_in_0_sel)) begin
        data_in_0_data_out = data_in_0_payload_B;
    end else begin
        data_in_0_data_out = data_in_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'd0 == exitcond_flatten_reg_1857) & (1'd1 == or_cond_reg_1893))) begin
        data_in_TDATA_blk_n = data_in_0_state[1'd0];
    end else begin
        data_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == data_out_1_sel)) begin
        data_out_1_data_out = data_out_1_payload_B;
    end else begin
        data_out_1_data_out = data_out_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter5) & (1'd1 == ap_reg_pp0_iter4_or_cond1_reg_1948) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        data_out_1_vld_in = 1'b1;
    end else begin
        data_out_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter5) & (1'd1 == ap_reg_pp0_iter4_or_cond1_reg_1948)) | ((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter6) & (1'd1 == ap_reg_pp0_iter5_or_cond1_reg_1948)))) begin
        data_out_TDATA_blk_n = data_out_1_state[1'd1];
    end else begin
        data_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        lines_b_V_0_ce0 = 1'b1;
    end else begin
        lines_b_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        lines_b_V_0_ce1 = 1'b1;
    end else begin
        lines_b_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
        lines_b_V_0_we1 = 1'b1;
    end else begin
        lines_b_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        lines_b_V_1_ce0 = 1'b1;
    end else begin
        lines_b_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        lines_b_V_1_ce1 = 1'b1;
    end else begin
        lines_b_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_or_cond_reg_1893))) begin
        lines_b_V_1_we1 = 1'b1;
    end else begin
        lines_b_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        lines_g_V_0_ce0 = 1'b1;
    end else begin
        lines_g_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        lines_g_V_0_ce1 = 1'b1;
    end else begin
        lines_g_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
        lines_g_V_0_we1 = 1'b1;
    end else begin
        lines_g_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        lines_g_V_1_ce0 = 1'b1;
    end else begin
        lines_g_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        lines_g_V_1_ce1 = 1'b1;
    end else begin
        lines_g_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_or_cond_reg_1893))) begin
        lines_g_V_1_we1 = 1'b1;
    end else begin
        lines_g_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        lines_r_V_0_ce0 = 1'b1;
    end else begin
        lines_r_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        lines_r_V_0_ce1 = 1'b1;
    end else begin
        lines_r_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
        lines_r_V_0_we1 = 1'b1;
    end else begin
        lines_r_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        lines_r_V_1_ce0 = 1'b1;
    end else begin
        lines_r_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        lines_r_V_1_ce1 = 1'b1;
    end else begin
        lines_r_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_or_cond_reg_1893))) begin
        lines_r_V_1_we1 = 1'b1;
    end else begin
        lines_r_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_b_V_0_2_loc_1_phi_fu_335_p4 = window_b_V_0_2_loc_2_reg_441;
    end else begin
        window_b_V_0_2_loc_1_phi_fu_335_p4 = window_b_V_0_2_loc_1_reg_332;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
        window_b_V_0_2_loc_2_phi_fu_446_p4 = lines_b_V_0_q0;
    end else begin
        window_b_V_0_2_loc_2_phi_fu_446_p4 = ap_phi_precharge_reg_pp0_iter2_window_b_V_0_2_loc_2_reg_441;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_b_V_1_2_loc_1_phi_fu_365_p4 = window_b_V_1_2_loc_2_reg_483;
    end else begin
        window_b_V_1_2_loc_1_phi_fu_365_p4 = window_b_V_1_2_loc_1_reg_362;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_1857))) begin
        window_b_V_2_2_loc_1_phi_fu_395_p4 = ap_reg_pp0_iter3_window_b_V_2_2_loc_2_reg_523;
    end else begin
        window_b_V_2_2_loc_1_phi_fu_395_p4 = window_b_V_2_2_loc_1_reg_392;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_g_V_0_2_loc_1_phi_fu_325_p4 = window_g_V_0_2_loc_2_reg_427;
    end else begin
        window_g_V_0_2_loc_1_phi_fu_325_p4 = window_g_V_0_2_loc_1_reg_322;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
        window_g_V_0_2_loc_2_phi_fu_432_p4 = lines_g_V_0_q0;
    end else begin
        window_g_V_0_2_loc_2_phi_fu_432_p4 = ap_phi_precharge_reg_pp0_iter2_window_g_V_0_2_loc_2_reg_427;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_g_V_1_2_loc_1_phi_fu_355_p4 = window_g_V_1_2_loc_2_reg_469;
    end else begin
        window_g_V_1_2_loc_1_phi_fu_355_p4 = window_g_V_1_2_loc_1_reg_352;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_1857))) begin
        window_g_V_2_2_loc_1_phi_fu_385_p4 = ap_reg_pp0_iter3_window_g_V_2_2_loc_2_reg_510;
    end else begin
        window_g_V_2_2_loc_1_phi_fu_385_p4 = window_g_V_2_2_loc_1_reg_382;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_r_V_0_2_loc_1_phi_fu_315_p4 = window_r_V_0_2_loc_2_reg_413;
    end else begin
        window_r_V_0_2_loc_1_phi_fu_315_p4 = window_r_V_0_2_loc_1_reg_312;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857) & (1'd1 == ap_reg_pp0_iter1_tmp_5_reg_1889))) begin
        window_r_V_0_2_loc_2_phi_fu_418_p4 = lines_r_V_0_q0;
    end else begin
        window_r_V_0_2_loc_2_phi_fu_418_p4 = ap_phi_precharge_reg_pp0_iter2_window_r_V_0_2_loc_2_reg_413;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_1857))) begin
        window_r_V_1_2_loc_1_phi_fu_345_p4 = window_r_V_1_2_loc_2_reg_455;
    end else begin
        window_r_V_1_2_loc_1_phi_fu_345_p4 = window_r_V_1_2_loc_1_reg_342;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_1857))) begin
        window_r_V_2_2_loc_1_phi_fu_375_p4 = ap_reg_pp0_iter3_window_r_V_2_2_loc_2_reg_497;
    end else begin
        window_r_V_2_2_loc_1_phi_fu_375_p4 = window_r_V_2_2_loc_1_reg_372;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'd0 == exitcond_flatten_reg_1857))) begin
        x_phi_fu_406_p4 = x_1_fu_741_p2;
    end else begin
        x_phi_fu_406_p4 = x_reg_402;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter6) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'd1 == exitcond_flatten_fu_584_p2) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter6) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'd1 == exitcond_flatten_fu_584_p2) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (data_out_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == data_in_0_vld_out) & (1'b1 == ap_predicate_op74_read_state3));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == data_in_0_vld_out) & (1'b1 == ap_predicate_op74_read_state3)) | ((1'b1 == ap_enable_reg_pp0_iter5) & (1'b1 == ap_block_state7_io)) | ((1'b1 == ap_enable_reg_pp0_iter6) & (1'b1 == ap_block_state8_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == data_in_0_vld_out) & (1'b1 == ap_predicate_op74_read_state3)) | ((1'b1 == ap_enable_reg_pp0_iter5) & (1'b1 == ap_block_state7_io)) | ((1'b1 == ap_enable_reg_pp0_iter6) & (1'b1 == ap_block_state8_io)));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((1'b0 == data_in_0_vld_out) & (1'b1 == ap_predicate_op74_read_state3));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((1'd1 == ap_reg_pp0_iter4_or_cond1_reg_1948) & (1'b0 == data_out_1_ack_in));
end

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((1'd1 == ap_reg_pp0_iter5_or_cond1_reg_1948) & (1'b0 == data_out_1_ack_in));
end

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_434 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00011001 == 1'b0));
end

always @ (*) begin
    ap_condition_609 = ((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_1857));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_precharge_reg_pp0_iter1_window_b_V_0_2_loc_2_reg_441 = 'bx;

assign ap_phi_precharge_reg_pp0_iter1_window_b_V_1_2_loc_2_reg_483 = 'bx;

assign ap_phi_precharge_reg_pp0_iter1_window_b_V_2_2_loc_2_reg_523 = 'bx;

assign ap_phi_precharge_reg_pp0_iter1_window_g_V_0_2_loc_2_reg_427 = 'bx;

assign ap_phi_precharge_reg_pp0_iter1_window_g_V_1_2_loc_2_reg_469 = 'bx;

assign ap_phi_precharge_reg_pp0_iter1_window_g_V_2_2_loc_2_reg_510 = 'bx;

assign ap_phi_precharge_reg_pp0_iter1_window_r_V_0_2_loc_2_reg_413 = 'bx;

assign ap_phi_precharge_reg_pp0_iter1_window_r_V_1_2_loc_2_reg_455 = 'bx;

assign ap_phi_precharge_reg_pp0_iter1_window_r_V_2_2_loc_2_reg_497 = 'bx;

always @ (*) begin
    ap_predicate_op74_read_state3 = ((1'd0 == exitcond_flatten_reg_1857) & (1'd1 == or_cond_reg_1893));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_in_0_ack_in = data_in_0_state[1'd1];

assign data_in_0_load_A = (data_in_0_state_cmp_full & ~data_in_0_sel_wr);

assign data_in_0_load_B = (data_in_0_sel_wr & data_in_0_state_cmp_full);

assign data_in_0_sel = data_in_0_sel_rd;

assign data_in_0_state_cmp_full = ((data_in_0_state != 2'd1) ? 1'b1 : 1'b0);

assign data_in_0_vld_in = data_in_TVALID;

assign data_in_0_vld_out = data_in_0_state[1'd0];

assign data_in_TREADY = data_in_0_state[1'd1];

assign data_out_1_ack_in = data_out_1_state[1'd1];

assign data_out_1_ack_out = data_out_TREADY;

assign data_out_1_load_A = (data_out_1_state_cmp_full & ~data_out_1_sel_wr);

assign data_out_1_load_B = (data_out_1_sel_wr & data_out_1_state_cmp_full);

assign data_out_1_sel = data_out_1_sel_rd;

assign data_out_1_state_cmp_full = ((data_out_1_state != 2'd1) ? 1'b1 : 1'b0);

assign data_out_1_vld_out = data_out_1_state[1'd0];

assign data_out_TDATA = data_out_1_data_out;

assign data_out_TVALID = data_out_1_state[1'd0];

assign data_out_b_V_addr_fu_1796_p4 = {{{tmp_30_fu_1789_p3}, {tmp_25_fu_1758_p3}}, {tmp_22_fu_1727_p3}};

assign exitcond_flatten_fu_584_p2 = ((indvar_flatten_reg_290 == 21'd2076601) ? 1'b1 : 1'b0);

assign exitcond_fu_596_p2 = ((x_phi_fu_406_p4 == 11'd1921) ? 1'b1 : 1'b0);

assign indvar_flatten_next_fu_590_p2 = (indvar_flatten_reg_290 + 21'd1);

assign lines_b_V_0_address0 = tmp_7_fu_661_p1;

assign lines_b_V_1_address0 = tmp_7_fu_661_p1;

assign lines_b_V_1_address1 = tmp_8_fu_878_p1;

assign lines_g_V_0_address0 = tmp_7_fu_661_p1;

assign lines_g_V_1_address0 = tmp_7_fu_661_p1;

assign lines_g_V_1_address1 = tmp_8_fu_878_p1;

assign lines_r_V_0_address0 = tmp_7_fu_661_p1;

assign lines_r_V_1_address0 = tmp_7_fu_661_p1;

assign lines_r_V_1_address1 = tmp_8_fu_878_p1;

assign or_cond1_fu_735_p2 = (tmp_9_fu_730_p2 & tmp_3_mid2_fu_656_p3);

assign or_cond_fu_650_p2 = (tmp_5_fu_644_p2 & tmp_1_mid2_fu_622_p3);

assign p_Val2_11_cast_fu_892_p1 = p_Val2_s_fu_884_p3;

assign p_Val2_1_0_1_cast_fu_928_p1 = p_Val2_1_0_1_fu_920_p3;

assign p_Val2_1_0_1_fu_920_p3 = {{window_r_V_0_2_loc_1_phi_fu_315_p4}, {8'd0}};

assign p_Val2_1_0_2_cast_fu_964_p1 = p_Val2_1_0_2_fu_956_p3;

assign p_Val2_1_0_2_fu_956_p3 = {{window_r_V_0_2_loc_2_phi_fu_418_p4}, {7'd0}};

assign p_Val2_1_1_1_fu_1052_p2 = (p_shl3_cast_fu_1048_p1 - p_shl2_cast_fu_1036_p1);

assign p_Val2_1_1_2_cast_fu_1264_p1 = p_Val2_1_1_2_fu_1256_p3;

assign p_Val2_1_1_2_fu_1256_p3 = {{window_r_V_1_2_loc_2_reg_455}, {8'd0}};

assign p_Val2_1_1_cast_fu_1000_p1 = p_Val2_1_1_fu_992_p3;

assign p_Val2_1_1_fu_992_p3 = {{window_r_V_1_1}, {8'd0}};

assign p_Val2_1_2_1_cast_fu_1336_p1 = p_Val2_1_2_1_fu_1328_p3;

assign p_Val2_1_2_1_fu_1328_p3 = {{window_r_V_2_2_loc_1_phi_fu_375_p4}, {8'd0}};

assign p_Val2_1_2_2_cast_fu_1126_p1 = p_Val2_1_2_2_fu_1118_p3;

assign p_Val2_1_2_2_fu_1118_p3 = {{ap_phi_precharge_reg_pp0_iter2_window_r_V_2_2_loc_2_reg_497}, {7'd0}};

assign p_Val2_1_2_cast_fu_1300_p1 = p_Val2_1_2_fu_1292_p3;

assign p_Val2_1_2_fu_1292_p3 = {{window_r_V_2_1}, {7'd0}};

assign p_Val2_1_fu_1624_p3 = ((tmp_19_fu_1619_p2[0:0] === 1'b1) ? p_sum_b_cast_fu_1612_p3 : p_Val2_8_2_2_cast_reg_2027);

assign p_Val2_2_2_2_cast_fu_1415_p2 = (tmp_s_fu_1405_p1 + tmp4_fu_1379_p2);

assign p_Val2_2_2_2_fu_1409_p2 = ($signed(tmp22_cast_fu_1385_p1) + $signed(tmp26_cast_fu_1401_p1));

assign p_Val2_2_fu_1600_p3 = ((tmp_14_fu_1595_p2[0:0] === 1'b1) ? p_sum_g_cast_fu_1588_p3 : p_Val2_5_2_2_cast_reg_2017);

assign p_Val2_4_0_1_cast_fu_940_p1 = p_Val2_4_0_1_fu_932_p3;

assign p_Val2_4_0_1_fu_932_p3 = {{window_g_V_0_2_loc_1_phi_fu_325_p4}, {8'd0}};

assign p_Val2_4_0_2_cast_fu_976_p1 = p_Val2_4_0_2_fu_968_p3;

assign p_Val2_4_0_2_fu_968_p3 = {{window_g_V_0_2_loc_2_phi_fu_432_p4}, {7'd0}};

assign p_Val2_4_1_1_fu_1082_p2 = (p_shl5_cast_fu_1078_p1 - p_shl4_cast_fu_1066_p1);

assign p_Val2_4_1_2_cast_fu_1276_p1 = p_Val2_4_1_2_fu_1268_p3;

assign p_Val2_4_1_2_fu_1268_p3 = {{window_g_V_1_2_loc_2_reg_469}, {8'd0}};

assign p_Val2_4_1_cast_fu_1012_p1 = p_Val2_4_1_fu_1004_p3;

assign p_Val2_4_1_fu_1004_p3 = {{window_g_V_1_1}, {8'd0}};

assign p_Val2_4_2_1_cast_fu_1348_p1 = p_Val2_4_2_1_fu_1340_p3;

assign p_Val2_4_2_1_fu_1340_p3 = {{window_g_V_2_2_loc_1_phi_fu_385_p4}, {8'd0}};

assign p_Val2_4_2_2_cast_fu_1162_p1 = p_Val2_4_2_2_fu_1154_p3;

assign p_Val2_4_2_2_fu_1154_p3 = {{ap_phi_precharge_reg_pp0_iter2_window_g_V_2_2_loc_2_reg_510}, {7'd0}};

assign p_Val2_4_2_cast_fu_1312_p1 = p_Val2_4_2_fu_1304_p3;

assign p_Val2_4_2_fu_1304_p3 = {{window_g_V_2_1}, {7'd0}};

assign p_Val2_4_cast_fu_904_p1 = p_Val2_4_fu_896_p3;

assign p_Val2_4_fu_896_p3 = {{window_g_V_0_1}, {7'd0}};

assign p_Val2_5_2_2_cast_fu_1472_p2 = (tmp_6_fu_1462_p1 + tmp11_fu_1436_p2);

assign p_Val2_5_2_2_fu_1466_p2 = ($signed(tmp30_cast_fu_1442_p1) + $signed(tmp34_cast_fu_1458_p1));

assign p_Val2_7_0_1_cast_fu_952_p1 = p_Val2_7_0_1_fu_944_p3;

assign p_Val2_7_0_1_fu_944_p3 = {{window_b_V_0_2_loc_1_phi_fu_335_p4}, {8'd0}};

assign p_Val2_7_0_2_cast_fu_988_p1 = p_Val2_7_0_2_fu_980_p3;

assign p_Val2_7_0_2_fu_980_p3 = {{window_b_V_0_2_loc_2_phi_fu_446_p4}, {7'd0}};

assign p_Val2_7_1_1_fu_1112_p2 = (p_shl7_cast_fu_1108_p1 - p_shl6_cast_fu_1096_p1);

assign p_Val2_7_1_2_cast_fu_1288_p1 = p_Val2_7_1_2_fu_1280_p3;

assign p_Val2_7_1_2_fu_1280_p3 = {{window_b_V_1_2_loc_2_reg_483}, {8'd0}};

assign p_Val2_7_1_cast_fu_1024_p1 = p_Val2_7_1_fu_1016_p3;

assign p_Val2_7_1_fu_1016_p3 = {{window_b_V_1_1}, {8'd0}};

assign p_Val2_7_2_1_cast_fu_1360_p1 = p_Val2_7_2_1_fu_1352_p3;

assign p_Val2_7_2_1_fu_1352_p3 = {{window_b_V_2_2_loc_1_phi_fu_395_p4}, {8'd0}};

assign p_Val2_7_2_2_cast_fu_1198_p1 = p_Val2_7_2_2_fu_1190_p3;

assign p_Val2_7_2_2_fu_1190_p3 = {{ap_phi_precharge_reg_pp0_iter2_window_b_V_2_2_loc_2_reg_523}, {7'd0}};

assign p_Val2_7_2_cast_fu_1324_p1 = p_Val2_7_2_fu_1316_p3;

assign p_Val2_7_2_fu_1316_p3 = {{window_b_V_2_1}, {7'd0}};

assign p_Val2_7_cast_fu_916_p1 = p_Val2_7_fu_908_p3;

assign p_Val2_7_fu_908_p3 = {{window_b_V_0_1}, {7'd0}};

assign p_Val2_8_2_2_cast_fu_1529_p2 = (tmp_10_fu_1519_p1 + tmp19_fu_1493_p2);

assign p_Val2_8_2_2_fu_1523_p2 = ($signed(tmp38_cast_fu_1499_p1) + $signed(tmp42_cast_fu_1515_p1));

assign p_Val2_s_6_fu_1576_p3 = ((tmp_12_fu_1571_p2[0:0] === 1'b1) ? p_sum_r_cast_fu_1564_p3 : p_Val2_2_2_2_cast_reg_2007);

assign p_Val2_s_fu_884_p3 = {{window_r_V_0_1}, {7'd0}};

assign p_shl2_cast_fu_1036_p1 = p_shl2_fu_1028_p3;

assign p_shl2_fu_1028_p3 = {{window_r_V_1_2_loc_1_phi_fu_345_p4}, {11'd0}};

assign p_shl3_cast_fu_1048_p1 = p_shl3_fu_1040_p3;

assign p_shl3_fu_1040_p3 = {{window_r_V_1_2_loc_1_phi_fu_345_p4}, {9'd0}};

assign p_shl4_cast_fu_1066_p1 = p_shl4_fu_1058_p3;

assign p_shl4_fu_1058_p3 = {{window_g_V_1_2_loc_1_phi_fu_355_p4}, {11'd0}};

assign p_shl5_cast_fu_1078_p1 = p_shl5_fu_1070_p3;

assign p_shl5_fu_1070_p3 = {{window_g_V_1_2_loc_1_phi_fu_355_p4}, {9'd0}};

assign p_shl6_cast_fu_1096_p1 = p_shl6_fu_1088_p3;

assign p_shl6_fu_1088_p3 = {{window_b_V_1_2_loc_1_phi_fu_365_p4}, {11'd0}};

assign p_shl7_cast_fu_1108_p1 = p_shl7_fu_1100_p3;

assign p_shl7_fu_1100_p3 = {{window_b_V_1_2_loc_1_phi_fu_365_p4}, {9'd0}};

assign p_sum_b_cast_fu_1612_p3 = ((tmp_31_reg_2044[0:0] === 1'b1) ? 20'd0 : 20'd261120);

assign p_sum_g_cast_fu_1588_p3 = ((tmp_29_reg_2038[0:0] === 1'b1) ? 20'd0 : 20'd261120);

assign p_sum_r_cast_fu_1564_p3 = ((tmp_27_reg_2032[0:0] === 1'b1) ? 20'd0 : 20'd261120);

assign ret_V_1_fu_1715_p2 = (8'd1 + ret_V_cast_reg_2065);

assign ret_V_3_fu_1746_p2 = (8'd1 + ret_V_2_cast_reg_2081);

assign ret_V_5_fu_1777_p2 = (8'd1 + ret_V_4_cast_reg_2097);

assign tmp10_fu_1431_p2 = (p_Val2_4_1_2_cast_fu_1276_p1 + tmp9_reg_1972);

assign tmp11_fu_1436_p2 = (tmp31_cast_fu_1427_p1 + tmp10_fu_1431_p2);

assign tmp12_fu_1172_p2 = (p_Val2_4_1_cast_fu_1012_p1 + p_Val2_4_cast_fu_904_p1);

assign tmp13_fu_1178_p2 = (18'd130048 + p_Val2_4_2_2_cast_fu_1162_p1);

assign tmp14_fu_1184_p2 = (p_Val2_4_0_2_cast_fu_976_p1 + tmp13_fu_1178_p2);

assign tmp15_fu_1452_p2 = (tmp35_cast_fu_1446_p1 + tmp36_cast_fu_1449_p1);

assign tmp16_fu_1478_p2 = (p_Val2_7_2_cast_fu_1324_p1 + p_Val2_7_2_1_cast_fu_1360_p1);

assign tmp17_fu_1202_p2 = (p_Val2_7_0_1_cast_fu_952_p1 + p_Val2_7_1_1_fu_1112_p2);

assign tmp18_fu_1488_p2 = (p_Val2_7_1_2_cast_fu_1288_p1 + tmp17_reg_1987);

assign tmp19_fu_1493_p2 = (tmp39_cast_fu_1484_p1 + tmp18_fu_1488_p2);

assign tmp1_fu_1364_p2 = (p_Val2_1_2_cast_fu_1300_p1 + p_Val2_1_2_1_cast_fu_1336_p1);

assign tmp20_fu_1208_p2 = (p_Val2_7_1_cast_fu_1024_p1 + p_Val2_7_cast_fu_916_p1);

assign tmp21_fu_1214_p2 = (18'd130048 + p_Val2_7_2_2_cast_fu_1198_p1);

assign tmp22_cast_fu_1385_p1 = $signed(tmp4_fu_1379_p2);

assign tmp22_fu_1220_p2 = (p_Val2_7_0_2_cast_fu_988_p1 + tmp21_fu_1214_p2);

assign tmp23_cast_fu_1370_p1 = tmp1_fu_1364_p2;

assign tmp23_fu_1509_p2 = (tmp43_cast_fu_1503_p1 + tmp44_cast_fu_1506_p1);

assign tmp26_cast_fu_1401_p1 = tmp8_fu_1395_p2;

assign tmp27_cast_fu_1389_p1 = tmp5_reg_1962;

assign tmp28_cast_fu_1392_p1 = tmp7_reg_1967;

assign tmp2_fu_1130_p2 = (p_Val2_1_0_1_cast_fu_928_p1 + p_Val2_1_1_1_fu_1052_p2);

assign tmp30_cast_fu_1442_p1 = $signed(tmp11_fu_1436_p2);

assign tmp31_cast_fu_1427_p1 = tmp_fu_1421_p2;

assign tmp34_cast_fu_1458_p1 = tmp15_fu_1452_p2;

assign tmp35_cast_fu_1446_p1 = tmp12_reg_1977;

assign tmp36_cast_fu_1449_p1 = tmp14_reg_1982;

assign tmp38_cast_fu_1499_p1 = $signed(tmp19_fu_1493_p2);

assign tmp39_cast_fu_1484_p1 = tmp16_fu_1478_p2;

assign tmp3_fu_1374_p2 = (p_Val2_1_1_2_cast_fu_1264_p1 + tmp2_reg_1957);

assign tmp42_cast_fu_1515_p1 = tmp23_fu_1509_p2;

assign tmp43_cast_fu_1503_p1 = tmp20_reg_1992;

assign tmp44_cast_fu_1506_p1 = tmp22_reg_1997;

assign tmp4_fu_1379_p2 = (tmp23_cast_fu_1370_p1 + tmp3_fu_1374_p2);

assign tmp5_fu_1136_p2 = (p_Val2_1_1_cast_fu_1000_p1 + p_Val2_11_cast_fu_892_p1);

assign tmp6_fu_1142_p2 = (18'd130048 + p_Val2_1_2_2_cast_fu_1126_p1);

assign tmp7_fu_1148_p2 = (p_Val2_1_0_2_cast_fu_964_p1 + tmp6_fu_1142_p2);

assign tmp8_fu_1395_p2 = (tmp27_cast_fu_1389_p1 + tmp28_cast_fu_1392_p1);

assign tmp9_fu_1166_p2 = (p_Val2_4_0_1_cast_fu_940_p1 + p_Val2_4_1_1_fu_1082_p2);

assign tmp_10_fu_1519_p1 = tmp23_fu_1509_p2;

assign tmp_11_fu_1559_p2 = (($signed(p_Val2_2_2_2_reg_2002) > $signed(21'd261120)) ? 1'b1 : 1'b0);

assign tmp_12_fu_1571_p2 = (tmp_27_reg_2032 | tmp_11_fu_1559_p2);

assign tmp_13_fu_1583_p2 = (($signed(p_Val2_5_2_2_reg_2012) > $signed(21'd261120)) ? 1'b1 : 1'b0);

assign tmp_14_fu_1595_p2 = (tmp_29_reg_2038 | tmp_13_fu_1583_p2);

assign tmp_15_fu_1607_p2 = (($signed(p_Val2_8_2_2_reg_2022) > $signed(21'd261120)) ? 1'b1 : 1'b0);

assign tmp_16_fu_1710_p2 = ((tmp_35_reg_2070 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_17_fu_1741_p2 = ((tmp_39_reg_2086 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_18_fu_1772_p2 = ((tmp_43_reg_2102 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_19_fu_1619_p2 = (tmp_31_reg_2044 | tmp_15_fu_1607_p2);

assign tmp_1_fu_572_p2 = ((y_reg_301 < 11'd1080) ? 1'b1 : 1'b0);

assign tmp_1_mid1_fu_616_p2 = ((y_s_fu_610_p2 < 11'd1080) ? 1'b1 : 1'b0);

assign tmp_1_mid2_fu_622_p3 = ((exitcond_fu_596_p2[0:0] === 1'b1) ? tmp_1_mid1_fu_616_p2 : tmp_1_fu_572_p2);

assign tmp_21_fu_1720_p3 = ((tmp_16_fu_1710_p2[0:0] === 1'b1) ? tmp_20_reg_2075 : ret_V_1_fu_1715_p2);

assign tmp_22_fu_1727_p3 = ((tmp_33_fu_1703_p3[0:0] === 1'b1) ? tmp_21_fu_1720_p3 : tmp_20_reg_2075);

assign tmp_24_fu_1751_p3 = ((tmp_17_fu_1741_p2[0:0] === 1'b1) ? tmp_23_reg_2091 : ret_V_3_fu_1746_p2);

assign tmp_25_fu_1758_p3 = ((tmp_37_fu_1734_p3[0:0] === 1'b1) ? tmp_24_fu_1751_p3 : tmp_23_reg_2091);

assign tmp_28_fu_1782_p3 = ((tmp_18_fu_1772_p2[0:0] === 1'b1) ? tmp_26_reg_2107 : ret_V_5_fu_1777_p2);

assign tmp_2_fu_688_p1 = data_in_0_data_out[7:0];

assign tmp_30_fu_1789_p3 = ((tmp_41_fu_1765_p3[0:0] === 1'b1) ? tmp_28_fu_1782_p3 : tmp_26_reg_2107);

assign tmp_33_fu_1703_p3 = p_Val2_s_6_reg_2050[32'd19];

assign tmp_35_fu_1641_p1 = p_Val2_s_6_fu_1576_p3[9:0];

assign tmp_37_fu_1734_p3 = p_Val2_2_reg_2055[32'd19];

assign tmp_39_fu_1665_p1 = p_Val2_2_fu_1600_p3[9:0];

assign tmp_3_fu_578_p2 = ((y_reg_301 != 11'd0) ? 1'b1 : 1'b0);

assign tmp_3_mid1_fu_630_p2 = ((y_s_fu_610_p2 != 11'd0) ? 1'b1 : 1'b0);

assign tmp_3_mid2_fu_656_p3 = ((exitcond_reg_1866[0:0] === 1'b1) ? tmp_3_mid1_reg_1879 : tmp_3_reg_1852);

assign tmp_41_fu_1765_p3 = p_Val2_1_reg_2060[32'd19];

assign tmp_43_fu_1689_p1 = p_Val2_1_fu_1624_p3[9:0];

assign tmp_5_fu_644_p2 = ((x_mid2_fu_602_p3 < 11'd1920) ? 1'b1 : 1'b0);

assign tmp_6_fu_1462_p1 = tmp15_fu_1452_p2;

assign tmp_7_fu_661_p1 = x_mid2_reg_1871;

assign tmp_8_fu_878_p1 = ap_reg_pp0_iter1_x_mid2_reg_1871;

assign tmp_9_fu_730_p2 = ((x_mid2_reg_1871 != 11'd0) ? 1'b1 : 1'b0);

assign tmp_fu_1421_p2 = (p_Val2_4_2_cast_fu_1312_p1 + p_Val2_4_2_1_cast_fu_1348_p1);

assign tmp_s_fu_1405_p1 = tmp8_fu_1395_p2;

assign x_1_fu_741_p2 = (x_mid2_reg_1871 + 11'd1);

assign x_mid2_fu_602_p3 = ((exitcond_fu_596_p2[0:0] === 1'b1) ? 11'd0 : x_phi_fu_406_p4);

assign y_mid2_fu_636_p3 = ((exitcond_fu_596_p2[0:0] === 1'b1) ? y_s_fu_610_p2 : y_reg_301);

assign y_s_fu_610_p2 = (y_reg_301 + 11'd1);

always @ (posedge ap_clk) begin
    tmp2_reg_1957[7:0] <= 8'b00000000;
    tmp5_reg_1962[6:0] <= 7'b0000000;
    tmp7_reg_1967[6:0] <= 7'b0000000;
    tmp9_reg_1972[7:0] <= 8'b00000000;
    tmp12_reg_1977[6:0] <= 7'b0000000;
    tmp14_reg_1982[6:0] <= 7'b0000000;
    tmp17_reg_1987[7:0] <= 8'b00000000;
    tmp20_reg_1992[6:0] <= 7'b0000000;
    tmp22_reg_1997[6:0] <= 7'b0000000;
    p_Val2_2_2_2_reg_2002[6:0] <= 7'b0000000;
    p_Val2_2_2_2_cast_reg_2007[6:0] <= 7'b0000000;
    p_Val2_5_2_2_reg_2012[6:0] <= 7'b0000000;
    p_Val2_5_2_2_cast_reg_2017[6:0] <= 7'b0000000;
    p_Val2_8_2_2_reg_2022[6:0] <= 7'b0000000;
    p_Val2_8_2_2_cast_reg_2027[6:0] <= 7'b0000000;
    p_Val2_s_6_reg_2050[6:0] <= 7'b0000000;
    p_Val2_2_reg_2055[6:0] <= 7'b0000000;
    p_Val2_1_reg_2060[6:0] <= 7'b0000000;
    tmp_35_reg_2070[6:0] <= 7'b0000000;
    tmp_39_reg_2086[6:0] <= 7'b0000000;
    tmp_43_reg_2102[6:0] <= 7'b0000000;
end

endmodule //filter_hls
