# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/vlsi1_010hs23/ex6/vivado/constraints/zybo-z7.xdc

# Block Designs: bd/zybo_top/zybo_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top || ORIG_REF_NAME==zybo_top}]

# IP: bd/zybo_top/ip/zybo_top_rgb2dvi_0/zybo_top_rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_rgb2dvi_0 || ORIG_REF_NAME==zybo_top_rgb2dvi_0}]

# IP: bd/zybo_top/ip/zybo_top_concat_0/zybo_top_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_concat_0 || ORIG_REF_NAME==zybo_top_concat_0}]

# IP: bd/zybo_top/ip/zybo_top_slice_vde_0/zybo_top_slice_vde_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_slice_vde_0 || ORIG_REF_NAME==zybo_top_slice_vde_0}]

# IP: bd/zybo_top/ip/zybo_top_slice_hsync_0/zybo_top_slice_hsync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_slice_hsync_0 || ORIG_REF_NAME==zybo_top_slice_hsync_0}]

# IP: bd/zybo_top/ip/zybo_top_slice_vsync_0/zybo_top_slice_vsync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_slice_vsync_0 || ORIG_REF_NAME==zybo_top_slice_vsync_0}]

# IP: bd/zybo_top/ip/zybo_top_slice_r_0/zybo_top_slice_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_slice_r_0 || ORIG_REF_NAME==zybo_top_slice_r_0}]

# IP: bd/zybo_top/ip/zybo_top_slice_g_0/zybo_top_slice_g_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_slice_g_0 || ORIG_REF_NAME==zybo_top_slice_g_0}]

# IP: bd/zybo_top/ip/zybo_top_slice_b_0/zybo_top_slice_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_slice_b_0 || ORIG_REF_NAME==zybo_top_slice_b_0}]

# IP: bd/zybo_top/ip/zybo_top_concat_rgb_0/zybo_top_concat_rgb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_concat_rgb_0 || ORIG_REF_NAME==zybo_top_concat_rgb_0}]

# IP: bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_clk_gen_0 || ORIG_REF_NAME==zybo_top_clk_gen_0}]

# IP: bd/zybo_top/ip/zybo_top_rst_gen_0/zybo_top_rst_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_rst_gen_0 || ORIG_REF_NAME==zybo_top_rst_gen_0}]

# IP: bd/zybo_top/ip/zybo_top_dvi2rgb_0/zybo_top_dvi2rgb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_dvi2rgb_0 || ORIG_REF_NAME==zybo_top_dvi2rgb_0}]

# IP: bd/zybo_top/ip/zybo_top_xlconcat_0_5/zybo_top_xlconcat_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_xlconcat_0_5 || ORIG_REF_NAME==zybo_top_xlconcat_0_5}]

# IP: bd/zybo_top/ip/zybo_top_xlslice_0_1/zybo_top_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_xlslice_0_1 || ORIG_REF_NAME==zybo_top_xlslice_0_1}]

# IP: bd/zybo_top/ip/zybo_top_data_slice_0/zybo_top_data_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_data_slice_0 || ORIG_REF_NAME==zybo_top_data_slice_0}]

# IP: bd/zybo_top/ip/zybo_top_data_slice_1/zybo_top_data_slice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_data_slice_1 || ORIG_REF_NAME==zybo_top_data_slice_1}]

# IP: bd/zybo_top/ip/zybo_top_data_slice_2/zybo_top_data_slice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_data_slice_2 || ORIG_REF_NAME==zybo_top_data_slice_2}]

# IP: bd/zybo_top/ip/zybo_top_r_slice_0/zybo_top_r_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_r_slice_0 || ORIG_REF_NAME==zybo_top_r_slice_0}]

# IP: bd/zybo_top/ip/zybo_top_r_slice_1/zybo_top_r_slice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_r_slice_1 || ORIG_REF_NAME==zybo_top_r_slice_1}]

# IP: bd/zybo_top/ip/zybo_top_fifo_generator_0_2/zybo_top_fifo_generator_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_fifo_generator_0_2 || ORIG_REF_NAME==zybo_top_fifo_generator_0_2}]

# IP: bd/zybo_top/ip/zybo_top_util_vector_logic_0_0/zybo_top_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_util_vector_logic_0_0 || ORIG_REF_NAME==zybo_top_util_vector_logic_0_0}]

# IP: bd/zybo_top/ip/zybo_top_fifo_generator_0_1/zybo_top_fifo_generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_fifo_generator_0_1 || ORIG_REF_NAME==zybo_top_fifo_generator_0_1}]

# IP: bd/zybo_top/ip/zybo_top_util_vector_logic_0_1/zybo_top_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_util_vector_logic_0_1 || ORIG_REF_NAME==zybo_top_util_vector_logic_0_1}]

# IP: bd/zybo_top/ip/zybo_top_xlconcat_0_0/zybo_top_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_xlconcat_0_0 || ORIG_REF_NAME==zybo_top_xlconcat_0_0}]

# IP: bd/zybo_top/ip/zybo_top_xlconstant_0_0/zybo_top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_xlconstant_0_0 || ORIG_REF_NAME==zybo_top_xlconstant_0_0}]

# IP: bd/zybo_top/ip/zybo_top_rgb_proc_wrap_0_0/zybo_top_rgb_proc_wrap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_rgb_proc_wrap_0_0 || ORIG_REF_NAME==zybo_top_rgb_proc_wrap_0_0}]

# IP: bd/zybo_top/ip/zybo_top_xlslice_0_0/zybo_top_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_xlslice_0_0 || ORIG_REF_NAME==zybo_top_xlslice_0_0}]

# IP: bd/zybo_top/ip/zybo_top_xlslice_0_2/zybo_top_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_top_xlslice_0_2 || ORIG_REF_NAME==zybo_top_xlslice_0_2}]

# XDC: bd/zybo_top/ip/zybo_top_rgb2dvi_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_rgb2dvi_0 || ORIG_REF_NAME==zybo_top_rgb2dvi_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_top/ip/zybo_top_rgb2dvi_0/src/rgb2dvi_ooc.xdc

# XDC: bd/zybo_top/ip/zybo_top_rgb2dvi_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_rgb2dvi_0 || ORIG_REF_NAME==zybo_top_rgb2dvi_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_clk_gen_0 || ORIG_REF_NAME==zybo_top_clk_gen_0}] {/inst }]/inst ]]

# XDC: bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_clk_gen_0 || ORIG_REF_NAME==zybo_top_clk_gen_0}] {/inst }]/inst ]]

# XDC: bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0_ooc.xdc

# XDC: bd/zybo_top/ip/zybo_top_dvi2rgb_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_dvi2rgb_0 || ORIG_REF_NAME==zybo_top_dvi2rgb_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_top/ip/zybo_top_dvi2rgb_0/src/dvi2rgb_ooc.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_dvi2rgb_0 || ORIG_REF_NAME==zybo_top_dvi2rgb_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_top/ip/zybo_top_fifo_generator_0_2/zybo_top_fifo_generator_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_fifo_generator_0_2 || ORIG_REF_NAME==zybo_top_fifo_generator_0_2}] {/U0 }]/U0 ]]

# XDC: bd/zybo_top/ip/zybo_top_fifo_generator_0_2/zybo_top_fifo_generator_0_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_fifo_generator_0_2 || ORIG_REF_NAME==zybo_top_fifo_generator_0_2}] {/U0 }]/U0 ]]

# XDC: bd/zybo_top/ip/zybo_top_fifo_generator_0_2/zybo_top_fifo_generator_0_2_ooc.xdc

# XDC: bd/zybo_top/ip/zybo_top_fifo_generator_0_1/zybo_top_fifo_generator_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_fifo_generator_0_1 || ORIG_REF_NAME==zybo_top_fifo_generator_0_1}] {/U0 }]/U0 ]]

# XDC: bd/zybo_top/ip/zybo_top_fifo_generator_0_1/zybo_top_fifo_generator_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_top_fifo_generator_0_1 || ORIG_REF_NAME==zybo_top_fifo_generator_0_1}] {/U0 }]/U0 ]]

# XDC: bd/zybo_top/ip/zybo_top_fifo_generator_0_1/zybo_top_fifo_generator_0_1_ooc.xdc

# XDC: bd/zybo_top/zybo_top_ooc.xdc
