# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -ruleid {1}  -id {BD 41-1731}  -new_severity {INFO} 
set_msg_config  -ruleid {2}  -id {BD 41-1306}  -new_severity {INFO} 
set_msg_config  -ruleid {3}  -id {BD 41-927}  -new_severity {INFO} 
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/vlsi1_010hs23/ex6/vivado/ex6.cache/wt [current_project]
set_property parent.project_path /home/vlsi1_010hs23/ex6/vivado/ex6.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths /home/vlsi1_010hs23/ex6/vivado/ip_repo [current_project]
set_property ip_output_repo /home/vlsi1_010hs23/ex6/vivado/ex6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/rst_gen.sv
  /home/vlsi1_010hs23/ex6/sourcecode/rgb_brightener.sv
  /home/vlsi1_010hs23/ex6/sourcecode/rgb_grayscaler_refined.sv
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/rgb_mux.sv
  /home/vlsi1_010hs23/ex6/sourcecode/rgb_proc.sv
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/rgb_reg.sv
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/rgb_spill_reg.sv
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/spill_register.sv
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/stream_demux.sv
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/stream_mux.sv
}
read_verilog -library xil_defaultlib {
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/rst_gen_wrap.v
  /home/vlsi1_010hs23/ex6/sourcecode/surrounding_modules/rgb_proc_wrap.v
  /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/hdl/zybo_top_wrapper.v
}
add_files /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/zybo_top.bd
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_rgb2dvi_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_dvi2rgb_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_dvi2rgb_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_fifo_generator_0_2/zybo_top_fifo_generator_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_fifo_generator_0_2/zybo_top_fifo_generator_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_fifo_generator_0_2/zybo_top_fifo_generator_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_fifo_generator_0_1/zybo_top_fifo_generator_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_fifo_generator_0_1/zybo_top_fifo_generator_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_fifo_generator_0_1/zybo_top_fifo_generator_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/zybo_top_ooc.xdc]
set_property is_locked true [get_files /home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/zybo_top.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/vlsi1_010hs23/ex6/vivado/constraints/zybo-z7.xdc
set_property used_in_implementation false [get_files /home/vlsi1_010hs23/ex6/vivado/constraints/zybo-z7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zybo_top_wrapper -part xc7z020clg400-1 -fanout_limit 400 -retiming -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef zybo_top_wrapper.dcp

catch { report_utilization -file zybo_top_wrapper_utilization_synth.rpt -pb zybo_top_wrapper_utilization_synth.pb }
