set_property SRC_FILE_INFO {cfile:/home/vlsi1_010hs23/ex6/vivado/ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0.xdc rfile:../../../ex6.srcs/sources_1/bd/zybo_top/ip/zybo_top_clk_gen_0/zybo_top_clk_gen_0.xdc id:1 order:EARLY scoped_inst:zybo_top_i/hdmi_rx/clk_gen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/vlsi1_010hs23/ex6/vivado/constraints/zybo-z7.xdc rfile:../../../constraints/zybo-z7.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K17  IOSTANDARD LVCMOS33 }     [get_ports { clk_i }];          #IO_L12P_T1_MRCC_35         Sch=sysclk
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G15  IOSTANDARD LVCMOS33 }     [get_ports { switch_i[0] }];    #IO_L19N_T3_VREF_35         Sch=sw[0]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P15  IOSTANDARD LVCMOS33 }     [get_ports { switch_i[1] }];    #IO_L24P_T3_34              Sch=sw[1]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W13  IOSTANDARD LVCMOS33 }     [get_ports { switch_i[2] }];    #IO_L4N_T0_34               Sch=sw[2]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T16  IOSTANDARD LVCMOS33 }     [get_ports { switch_i[3] }];    #IO_L9P_T1_DQS_34           Sch=sw[3]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K18  IOSTANDARD LVCMOS33 }     [get_ports { btn_i[0] }];       #IO_L12N_T1_MRCC_35         Sch=btn[0]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P16  IOSTANDARD LVCMOS33 }     [get_ports { btn_i[1] }];       #IO_L24N_T3_34              Sch=btn[1]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K19  IOSTANDARD LVCMOS33 }     [get_ports { btn_i[2] }];       #IO_L10P_T1_AD11P_35        Sch=btn[2]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y16  IOSTANDARD LVCMOS33 }     [get_ports { btn_i[3] }];       #IO_L7P_T1_34               Sch=btn[3]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14  IOSTANDARD LVCMOS33 }     [get_ports { led_o[0] }];       #IO_L23P_T3_35              Sch=led[0]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M15  IOSTANDARD LVCMOS33 }     [get_ports { led_o[1] }];       #IO_L23N_T3_35              Sch=led[1]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G14  IOSTANDARD LVCMOS33 }     [get_ports { led_o[2] }];       #IO_0_35                    Sch=led[2]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D18  IOSTANDARD LVCMOS33 }     [get_ports { led_o[3] }];       #IO_L3N_T0_DQS_AD1N_35      Sch=led[3]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W19  IOSTANDARD LVCMOS33 }     [get_ports { hdmi_rx_hpd_o }];      #IO_L22N_T3_34          Sch=hdmi_rx_hpd
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W18  IOSTANDARD LVCMOS33 }     [get_ports { hdmi_rx_ddc_scl_io }]; #IO_L22P_T3_34          Sch=hdmi_rx_scl
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y19  IOSTANDARD LVCMOS33 }     [get_ports { hdmi_rx_ddc_sda_io }]; #IO_L17N_T2_34          Sch=hdmi_rx_sda
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U19  IOSTANDARD TMDS_33 }      [get_ports { hdmi_rx_clk_n_i }];    #IO_L12N_T1_MRCC_34     Sch=hdmi_rx_clk_n
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U18  IOSTANDARD TMDS_33 }      [get_ports { hdmi_rx_clk_p_i }];    #IO_L12P_T1_MRCC_34     Sch=hdmi_rx_clk_p
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W20  IOSTANDARD TMDS_33 }      [get_ports { hdmi_rx_n_i[0] }];     #IO_L16N_T2_34          Sch=hdmi_rx_n[0]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V20  IOSTANDARD TMDS_33 }      [get_ports { hdmi_rx_p_i[0] }];     #IO_L16P_T2_34          Sch=hdmi_rx_p[0]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U20  IOSTANDARD TMDS_33 }      [get_ports { hdmi_rx_n_i[1] }];     #IO_L15N_T2_DQS_34      Sch=hdmi_rx_n[1]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T20  IOSTANDARD TMDS_33 }      [get_ports { hdmi_rx_p_i[1] }];     #IO_L15P_T2_DQS_34      Sch=hdmi_rx_p[1]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P20  IOSTANDARD TMDS_33 }      [get_ports { hdmi_rx_n_i[2] }];     #IO_L14N_T2_SRCC_34     Sch=hdmi_rx_n[2]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N20  IOSTANDARD TMDS_33 }      [get_ports { hdmi_rx_p_i[2] }];     #IO_L14P_T2_SRCC_34     Sch=hdmi_rx_p[2]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17  IOSTANDARD TMDS_33  }     [get_ports { hdmi_tx_clk_n_o }];    #IO_L13N_T2_MRCC_35     Sch=hdmi_tx_clk_n
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16  IOSTANDARD TMDS_33  }     [get_ports { hdmi_tx_clk_p_o }];    #IO_L13P_T2_MRCC_35     Sch=hdmi_tx_clk_p
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D20  IOSTANDARD TMDS_33  }     [get_ports { hdmi_tx_n_o[0] }];     #IO_L4N_T0_35           Sch=hdmi_tx_n[0]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19  IOSTANDARD TMDS_33  }     [get_ports { hdmi_tx_p_o[0] }];     #IO_L4P_T0_35           Sch=hdmi_tx_p[0]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B20  IOSTANDARD TMDS_33  }     [get_ports { hdmi_tx_n_o[1] }];     #IO_L1N_T0_AD0N_35      Sch=hdmi_tx_n[1]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C20  IOSTANDARD TMDS_33  }     [get_ports { hdmi_tx_p_o[1] }];     #IO_L1P_T0_AD0P_35      Sch=hdmi_tx_p[1]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A20  IOSTANDARD TMDS_33  }     [get_ports { hdmi_tx_n_o[2] }];     #IO_L2N_T0_AD8N_35      Sch=hdmi_tx_n[2]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B19  IOSTANDARD TMDS_33  }     [get_ports { hdmi_tx_p_o[2] }];     #IO_L2P_T0_AD8P_35      Sch=hdmi_tx_p[2]
